name: Release

on: 
  workflow_dispatch

jobs:
  
  push_to_steam:
    name: Upload mod to steam workshop
    runs-on: ubuntu-latest
    #needs: [release]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        
      - name: Upload the mod to Steam Workshop
        uses: IsaacScript/isaac-steam-workshop-upload@v2
        with:
          mod_path: .
          change_note: "Changes for this mod are [url=https://github.com/wofsauge/External-Item-Descriptions/releases]tracked on GitHub[/url]."
        env:
          CONFIG_VDF_CONTENTS: ${{ secrets.CONFIG_VDF_CONTENTS }}
